export const FIND_ALL_ACTION = "FIND_ALL_FILES_ACTION";
export const FETCH_SUCCESS = "FETCH_FILE_SUCCESS";
export const FETCH_REQUEST = "FETCH_FILE_REQUEST";
export const FETCH_FAILURE = "FETCH_FILE_FAILURE";

export const ADD_ACTION = 'ADD_FILE_ACTION';
export const EDIT_ACTION = 'EDIT_FILE_ACTION';
export const DELETE_ACTION = 'DELETE_FILE_ACTION';
export const SHOW_ACTION = 'SHOW_FILE_ACTION';

export const DISPLAY_ACTION = "DISPLAY_FILE_ACTION";