
//SETTINGS
export const SERVER_URL = "http://localhost:1337"

//LOGIN_ACTION
export const LOGIN_ACTION = "LOGIN_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";

//FILTER_ACTION
export const FILTER_ACTION = "FILTER_ACTION";
export const SHOW_ALL_FILTER = "SHOW_ALL_FILTER";
export const SHOW_BY_DATE_FILTER  = "SHOW_BY_DATE_FILTER";
