
//CRUD
export const ADD_ACTION = 'ADD_ACTION';
export const EDIT_ACTION = 'EDIT_ACTION';
export const DELETE_ACTION = 'DELETE_ACTION';
export const FIND_ALL_ACTION = "FIND_ALL_ACTION";

//STATUS ACTIONS
export const SUCCESS_STORAGES = "SUCCESS_STORAGES";
export const REQUEST_STORAGES = "REQUEST_STORAGES";
export const FAILURE_STORAGES = "FAILURE_STORAGES";

//CUSTOM ACTIONS
export const SHOW_ACTION = 'SHOW_ACTION';
