export const ADD_ACTION = "ADD_ACTION";
export const EDIT_ACTION = "EDIT_ACTION";
export const DELETE_ACTION = "DELETE_ACTION";

export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";

//USER ACTION
export const REQUEST_USER_DATA = "REQUEST_USER_DATA"; 
export const SUCCESS_USER_DATA = "SUCCESS_USER_DATA"; 
export const FAILURE_USER_DATA = "FAILURE_USER_DATA";